<?php
/**
 * Doofinder build-time constants.
 *
 * +-----------------------------------------------------------------+
 * |              ** AUTOGENERATED FILE WARNING **                   |
 * | DO NOT EDIT this file directly. It is regenerated from         |
 * | templates/.../includes/class-doofinder-constants.php            |
 * | by `make doofinder-configure`.                                  |
 * +-----------------------------------------------------------------+
 *
 * @package Doofinder\WP
 */

namespace Doofinder\WP;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Build-time constants populated by envsubst from `.env`.
 */
class Doofinder_Constants {

	const VERSION            = '2.15.2';
	const PLUGINS_URL_FORMAT = 'https://%splugins.doofinder.com';
	const API_URL_FORMAT     = 'https://%sadmin.doofinder.com';
}
