<?php
/**
 * Doofinder build-time constants.
 *
 * +-----------------------------------------------------------------+
 * |              ** AUTOGENERATED FILE WARNING **                   |
 * | DO NOT EDIT this file directly. It is regenerated from          |
 * | templates/doofinder-for-woocommerce/includes/class-constants.php|
 * | by `make doofinder-configure`.                                  |
 * +-----------------------------------------------------------------+
 *
 * @package Doofinder\WP
 */

namespace Doofinder\WP;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Build-time constants populated by envsubst from `.env`.
 */
class Doofinder_Constants {

	const VERSION             = '${PLUGIN_VERSION}';
	const PLUGINS_URL_FORMAT  = '${DOOFINDER_PLUGINS_URL_FORMAT}';
	const API_URL_FORMAT      = '${DOOFINDER_API_URL_FORMAT}';
}
