name: PHP tests
on: [push, pull_request]
jobs:
  phplint:
    name: PHP Syntax check 7.0 -> 8.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: PHP Lint 7.2
        uses: dbfx/github-phplint/7.2@master
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP Lint 7.3
        uses: dbfx/github-phplint/7.3@master
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP Lint 7.4
        uses: dbfx/github-phplint/7.4@master
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP Lint 8.0
        uses: dbfx/github-phplint/8.0@master
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP Lint 8.1
        uses: dbfx/github-phplint/8.1@master
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP Lint 8.2
        uses: dbfx/github-phplint/8.2@master
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP Lint 8.3
        uses: dbfx/github-phplint/8.3@master
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP Lint 8.4
        uses: dbfx/github-phplint/8.4@master
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
  phpcs:
    name: WordPress and WooCommerce PHP code standards compliance check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important!
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: install
      - name: Standards Compliance check
        run: ./vendor/bin/phpcs
